# Generated by Django 5.0.6 on 2025-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreMedicamento', models.CharField(max_length=255)),
                ('cantidadStock', models.IntegerField(max_length=255)),
                ('cantDispensada', models.IntegerField(max_length=255)),
                ('cantIngresada', models.IntegerField(max_length=255)),
            ],
        ),
    ]
