# Generated by Django 5.2.1 on 2025-07-21 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreMedicamento', models.CharField(max_length=255)),
                ('cantidadStock', models.IntegerField(max_length=255)),
                ('cantDispensada', models.IntegerField(max_length=255)),
                ('fechaIngreso', models.DateField()),
                ('fechaVencimiento', models.DateField()),
            ],
        ),
    ]
