# Generated by Django 5.2.1 on 2025-08-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamentos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
