# Generated by Django 5.0.6 on 2025-08-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('proceso', models.IntegerField(max_length=255)),
            ],
        ),
    ]
