# Generated by Django 5.0.6 on 2025-08-17 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reciclados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='proceso',
            field=models.TextField(max_length=500),
        ),
    ]
